### ISSUE TITLE
Conflict with go crypto/x509

### ISSUE THREAD

**Issue by joosep-wm** [github/ietf-cms#6]
Hi

I'm trying out your library and stumbled upon a problem:

../../../../mastahyeti/cms/verify.go:151:86: unknown field 'Detail' in struct literal of type x509.CertificateInvalidError

Seems if you'd just remove the "Detail", it would work.

**Comment by btoews** [comment]
Thanks for opening this. What version of go are you running (`go version`)? There are a number of things in this library that don't work with versions prior to 1.10.0.

**Comment by joosep-wm** [comment]
$ go version
go version go1.10.2 darwin/amd64

**Comment by btoews** [comment]
Hmm. Are you sure about that version number? [Here's](https://github.com/golang/go/blob/go1.10.2/src/crypto/x509/verify.go#L64-L70) the definition of that struct from 1.10.2:

```go
// CertificateInvalidError results when an odd error occurs. Users of this
// library probably want to handle all these errors uniformly.
type CertificateInvalidError struct {
	Cert   *Certificate
	Reason InvalidReason
	Detail string
}
```

**Comment by joosep-wm** [comment]
You are absolutely right.
My IDE used the old Go version. Somehow I thought it takes the Go version from my shell environment.

When using new Go version, it works nicely.
